//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from RAGE.g4 by ANTLR 4.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="RAGEParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6")]
[System.CLSCompliant(false)]
public interface IRAGEListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpression([NotNull] RAGEParser.PrimaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpression([NotNull] RAGEParser.PrimaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfixExpression([NotNull] RAGEParser.PostfixExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfixExpression([NotNull] RAGEParser.PostfixExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.argumentExpressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentExpressionList([NotNull] RAGEParser.ArgumentExpressionListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.argumentExpressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentExpressionList([NotNull] RAGEParser.ArgumentExpressionListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpression([NotNull] RAGEParser.UnaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpression([NotNull] RAGEParser.UnaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryOperator([NotNull] RAGEParser.UnaryOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryOperator([NotNull] RAGEParser.UnaryOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.castExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCastExpression([NotNull] RAGEParser.CastExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.castExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCastExpression([NotNull] RAGEParser.CastExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpression([NotNull] RAGEParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpression([NotNull] RAGEParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpression([NotNull] RAGEParser.AdditiveExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpression([NotNull] RAGEParser.AdditiveExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.shiftExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShiftExpression([NotNull] RAGEParser.ShiftExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.shiftExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShiftExpression([NotNull] RAGEParser.ShiftExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpression([NotNull] RAGEParser.RelationalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpression([NotNull] RAGEParser.RelationalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityExpression([NotNull] RAGEParser.EqualityExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityExpression([NotNull] RAGEParser.EqualityExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpression([NotNull] RAGEParser.AndExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpression([NotNull] RAGEParser.AndExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.exclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExclusiveOrExpression([NotNull] RAGEParser.ExclusiveOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.exclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExclusiveOrExpression([NotNull] RAGEParser.ExclusiveOrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.inclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInclusiveOrExpression([NotNull] RAGEParser.InclusiveOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.inclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInclusiveOrExpression([NotNull] RAGEParser.InclusiveOrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalAndExpression([NotNull] RAGEParser.LogicalAndExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalAndExpression([NotNull] RAGEParser.LogicalAndExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOrExpression([NotNull] RAGEParser.LogicalOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOrExpression([NotNull] RAGEParser.LogicalOrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalExpression([NotNull] RAGEParser.ConditionalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalExpression([NotNull] RAGEParser.ConditionalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentExpression([NotNull] RAGEParser.AssignmentExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentExpression([NotNull] RAGEParser.AssignmentExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentOperator([NotNull] RAGEParser.AssignmentOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentOperator([NotNull] RAGEParser.AssignmentOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] RAGEParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] RAGEParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.constantExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstantExpression([NotNull] RAGEParser.ConstantExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.constantExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstantExpression([NotNull] RAGEParser.ConstantExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.globalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlobalExpression([NotNull] RAGEParser.GlobalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.globalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlobalExpression([NotNull] RAGEParser.GlobalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] RAGEParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] RAGEParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.declarationSpecifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationSpecifiers([NotNull] RAGEParser.DeclarationSpecifiersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.declarationSpecifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationSpecifiers([NotNull] RAGEParser.DeclarationSpecifiersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.declarationSpecifiers2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationSpecifiers2([NotNull] RAGEParser.DeclarationSpecifiers2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.declarationSpecifiers2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationSpecifiers2([NotNull] RAGEParser.DeclarationSpecifiers2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.declarationSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationSpecifier([NotNull] RAGEParser.DeclarationSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.declarationSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationSpecifier([NotNull] RAGEParser.DeclarationSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.initDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitDeclaratorList([NotNull] RAGEParser.InitDeclaratorListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.initDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitDeclaratorList([NotNull] RAGEParser.InitDeclaratorListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.initDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitDeclarator([NotNull] RAGEParser.InitDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.initDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitDeclarator([NotNull] RAGEParser.InitDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.storageClassSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStorageClassSpecifier([NotNull] RAGEParser.StorageClassSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.storageClassSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStorageClassSpecifier([NotNull] RAGEParser.StorageClassSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeSpecifier([NotNull] RAGEParser.TypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeSpecifier([NotNull] RAGEParser.TypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.structOrUnionSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructOrUnionSpecifier([NotNull] RAGEParser.StructOrUnionSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.structOrUnionSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructOrUnionSpecifier([NotNull] RAGEParser.StructOrUnionSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.structOrUnion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructOrUnion([NotNull] RAGEParser.StructOrUnionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.structOrUnion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructOrUnion([NotNull] RAGEParser.StructOrUnionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.arrayDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayDeclarator([NotNull] RAGEParser.ArrayDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.arrayDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayDeclarator([NotNull] RAGEParser.ArrayDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.arrayDeclarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayDeclarationList([NotNull] RAGEParser.ArrayDeclarationListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.arrayDeclarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayDeclarationList([NotNull] RAGEParser.ArrayDeclarationListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.arrayDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayDeclaration([NotNull] RAGEParser.ArrayDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.arrayDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayDeclaration([NotNull] RAGEParser.ArrayDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.structDeclarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructDeclarationList([NotNull] RAGEParser.StructDeclarationListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.structDeclarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructDeclarationList([NotNull] RAGEParser.StructDeclarationListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.structDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructDeclaration([NotNull] RAGEParser.StructDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.structDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructDeclaration([NotNull] RAGEParser.StructDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.specifierQualifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecifierQualifierList([NotNull] RAGEParser.SpecifierQualifierListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.specifierQualifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecifierQualifierList([NotNull] RAGEParser.SpecifierQualifierListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.structDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructDeclaratorList([NotNull] RAGEParser.StructDeclaratorListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.structDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructDeclaratorList([NotNull] RAGEParser.StructDeclaratorListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.structDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructDeclarator([NotNull] RAGEParser.StructDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.structDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructDeclarator([NotNull] RAGEParser.StructDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.enumDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumDeclarator([NotNull] RAGEParser.EnumDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.enumDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumDeclarator([NotNull] RAGEParser.EnumDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.enumSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumSpecifier([NotNull] RAGEParser.EnumSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.enumSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumSpecifier([NotNull] RAGEParser.EnumSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.enumeratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumeratorList([NotNull] RAGEParser.EnumeratorListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.enumeratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumeratorList([NotNull] RAGEParser.EnumeratorListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.enumerator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumerator([NotNull] RAGEParser.EnumeratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.enumerator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumerator([NotNull] RAGEParser.EnumeratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.enumerationConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumerationConstant([NotNull] RAGEParser.EnumerationConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.enumerationConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumerationConstant([NotNull] RAGEParser.EnumerationConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.typeQualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeQualifier([NotNull] RAGEParser.TypeQualifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.typeQualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeQualifier([NotNull] RAGEParser.TypeQualifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarator([NotNull] RAGEParser.DeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarator([NotNull] RAGEParser.DeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.directDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirectDeclarator([NotNull] RAGEParser.DirectDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.directDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirectDeclarator([NotNull] RAGEParser.DirectDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.nestedParenthesesBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNestedParenthesesBlock([NotNull] RAGEParser.NestedParenthesesBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.nestedParenthesesBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNestedParenthesesBlock([NotNull] RAGEParser.NestedParenthesesBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.pointer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointer([NotNull] RAGEParser.PointerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.pointer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointer([NotNull] RAGEParser.PointerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.typeQualifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeQualifierList([NotNull] RAGEParser.TypeQualifierListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.typeQualifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeQualifierList([NotNull] RAGEParser.TypeQualifierListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.parameterTypeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterTypeList([NotNull] RAGEParser.ParameterTypeListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.parameterTypeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterTypeList([NotNull] RAGEParser.ParameterTypeListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterList([NotNull] RAGEParser.ParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterList([NotNull] RAGEParser.ParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.parameterDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterDeclaration([NotNull] RAGEParser.ParameterDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.parameterDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterDeclaration([NotNull] RAGEParser.ParameterDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.identifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifierList([NotNull] RAGEParser.IdentifierListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.identifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifierList([NotNull] RAGEParser.IdentifierListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeName([NotNull] RAGEParser.TypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeName([NotNull] RAGEParser.TypeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.abstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbstractDeclarator([NotNull] RAGEParser.AbstractDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.abstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbstractDeclarator([NotNull] RAGEParser.AbstractDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.typedefName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypedefName([NotNull] RAGEParser.TypedefNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.typedefName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypedefName([NotNull] RAGEParser.TypedefNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitializer([NotNull] RAGEParser.InitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitializer([NotNull] RAGEParser.InitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.initializerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitializerList([NotNull] RAGEParser.InitializerListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.initializerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitializerList([NotNull] RAGEParser.InitializerListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.designation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDesignation([NotNull] RAGEParser.DesignationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.designation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDesignation([NotNull] RAGEParser.DesignationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.designatorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDesignatorList([NotNull] RAGEParser.DesignatorListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.designatorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDesignatorList([NotNull] RAGEParser.DesignatorListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDesignator([NotNull] RAGEParser.DesignatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDesignator([NotNull] RAGEParser.DesignatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.selectionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectionStatement([NotNull] RAGEParser.SelectionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.selectionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectionStatement([NotNull] RAGEParser.SelectionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.selectionElseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectionElseStatement([NotNull] RAGEParser.SelectionElseStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.selectionElseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectionElseStatement([NotNull] RAGEParser.SelectionElseStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] RAGEParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] RAGEParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.labeledStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabeledStatement([NotNull] RAGEParser.LabeledStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.labeledStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabeledStatement([NotNull] RAGEParser.LabeledStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.compoundStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompoundStatement([NotNull] RAGEParser.CompoundStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.compoundStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompoundStatement([NotNull] RAGEParser.CompoundStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.blockItemList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockItemList([NotNull] RAGEParser.BlockItemListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.blockItemList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockItemList([NotNull] RAGEParser.BlockItemListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.blockItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockItem([NotNull] RAGEParser.BlockItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.blockItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockItem([NotNull] RAGEParser.BlockItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionStatement([NotNull] RAGEParser.ExpressionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionStatement([NotNull] RAGEParser.ExpressionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.iterationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIterationStatement([NotNull] RAGEParser.IterationStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.iterationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIterationStatement([NotNull] RAGEParser.IterationStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJumpStatement([NotNull] RAGEParser.JumpStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJumpStatement([NotNull] RAGEParser.JumpStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompilationUnit([NotNull] RAGEParser.CompilationUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompilationUnit([NotNull] RAGEParser.CompilationUnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.translationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTranslationUnit([NotNull] RAGEParser.TranslationUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.translationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTranslationUnit([NotNull] RAGEParser.TranslationUnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.externalDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExternalDeclaration([NotNull] RAGEParser.ExternalDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.externalDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExternalDeclaration([NotNull] RAGEParser.ExternalDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDefinition([NotNull] RAGEParser.FunctionDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDefinition([NotNull] RAGEParser.FunctionDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.declarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationList([NotNull] RAGEParser.DeclarationListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.declarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationList([NotNull] RAGEParser.DeclarationListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAGEParser.includeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncludeExpression([NotNull] RAGEParser.IncludeExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAGEParser.includeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncludeExpression([NotNull] RAGEParser.IncludeExpressionContext context);
}
